'use client'

import { useChat } from '@ai-sdk/react'
import { Activity, ArrowUp, BrainCircuit, ChevronRight, CirclePause, FileText, GitBranch, Menu, Network, Pause, Play, Plus, Shield, Sparkles, X, Zap } from 'lucide-react'
import { useState } from 'react'
import { demoSnapshot } from '@/lib/sam/snapshot'
import type { SamActivity } from '@/lib/sam/types'

const commands = ['Run ecosystem health check', 'Explain the highest project risk', 'Review latest plan changes']

export default function Home() {
  const [mobileNav, setMobileNav] = useState(false)
  const [input, setInput] = useState('')
  const [paused, setPaused] = useState(false)
  const { messages, sendMessage, status, error, setMessages } = useChat()
  const busy = status === 'submitted' || status === 'streaming'
  const snapshot = { ...demoSnapshot, mode: paused ? 'paused' as const : demoSnapshot.mode }

  async function runCommand(command = input) {
    const value = command.trim()
    if (!value || busy) return
    setInput('')
    await sendMessage({ text: value })
  }

  return <main className="min-h-dvh bg-background text-foreground">
    <header className="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-line/80 bg-background/95 px-4 backdrop-blur sm:px-8">
      <div className="flex items-center gap-3"><button className="flex size-11 items-center justify-center rounded-xl border border-line md:hidden" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={18} /></button><div className="flex size-9 items-center justify-center rounded-xl bg-accent text-background"><BrainCircuit size={19} /></div><div><p className="text-[11px] font-bold tracking-[.22em] text-accent">BUILDVISION</p><p className="text-sm font-semibold tracking-tight">S.A.M. control plane</p></div></div>
      <div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full border border-accent/20 bg-accent-soft px-3 py-1.5 text-xs font-medium text-accent sm:flex"><span className="size-1.5 rounded-full bg-accent" /> Autonomous</span><button onClick={() => setPaused(!paused)} className="flex min-h-11 items-center gap-2 rounded-xl border border-line px-3 text-xs font-semibold hover:bg-panel" aria-label={paused ? 'Resume autonomy' : 'Pause autonomy'}>{paused ? <Play size={14} /> : <Pause size={14} />}<span className="hidden sm:inline">{paused ? 'Resume' : 'Pause'}</span></button></div>
    </header>

    <div className="mx-auto flex w-full max-w-[1500px]">
      <aside className={`${mobileNav ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-[290px] border-r border-line bg-panel p-5 transition-transform md:static md:translate-x-0 md:bg-transparent`}><div className="mb-8 flex items-center justify-between md:hidden"><span className="font-semibold">Control surfaces</span><button onClick={() => setMobileNav(false)} className="flex size-11 items-center justify-center rounded-xl border border-line" aria-label="Close navigation"><X size={18} /></button></div><p className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[.2em] text-muted">Operating surfaces</p><nav className="space-y-1"><SideItem icon={<Activity size={17} />} label="Command room" active /><SideItem icon={<Network size={17} />} label="Ecosystem graph" /><SideItem icon={<Zap size={17} />} label="Autonomous runs" /><SideItem icon={<Shield size={17} />} label="Governance & overrides" /></nav><p className="mb-3 mt-9 px-2 text-[10px] font-bold uppercase tracking-[.2em] text-muted">Connected systems</p><div className="space-y-1"><SystemRow label="Projects & documents" status="nominal" /><SystemRow label="GitHub" status="degraded" icon={<GitBranch size={15} />} /><SystemRow label="Vercel" status="degraded" /></div><div className="mt-10 rounded-2xl border border-line bg-panel p-4"><p className="text-xs font-semibold">Founder override</p><p className="mt-1 text-xs leading-relaxed text-muted">You are the final authority. S.A.M. records every decision and respects your deny rules.</p><button className="mt-4 flex min-h-11 w-full items-center justify-between rounded-xl bg-panel-strong px-3 text-xs font-semibold">Manage policy <ChevronRight size={15} /></button></div></aside>
      {mobileNav && <button className="fixed inset-0 z-30 bg-black/50 md:hidden" onClick={() => setMobileNav(false)} aria-label="Close navigation overlay" />}

      <section className="min-w-0 flex-1 px-4 py-5 sm:px-8 sm:py-8"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Strategic AI Manager</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.04em] sm:text-4xl">Good morning, Jordan.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted">S.A.M. is observing the BuildVision ecosystem and coordinating the next best actions.</p></div><button onClick={() => setMessages([])} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl border border-line px-3 text-xs font-semibold hover:bg-panel"><Plus size={15} /> <span className="hidden sm:inline">New run</span></button></div>
        <div className="grid gap-4 xl:grid-cols-[1.45fr_1fr]">
          <div className="space-y-4"><div className="rounded-2xl border border-accent/20 bg-panel p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="relative flex size-12 items-center justify-center"><div className="orb-ring absolute inset-0 rounded-full border border-accent/40" /><div className="orb-core flex size-8 items-center justify-center rounded-full bg-accent text-background"><Sparkles size={16} /></div></div><div><p className="font-semibold">S.A.M. is on watch</p><p className="text-xs text-muted">Founder-level orchestration active</p></div></div><span className="rounded-full bg-accent-soft px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-accent">{snapshot.mode}</span></div><div className="mt-6 rounded-xl border border-line bg-background/60 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold">{snapshot.activeRun?.title}</p><p className="mt-1 text-xs text-muted">{snapshot.activeRun?.phase}</p></div><span className="text-xs font-semibold text-accent">{snapshot.activeRun?.progress}%</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-panel-strong"><div className="h-full rounded-full bg-accent" style={{ width: `${snapshot.activeRun?.progress}%` }} /></div><p className="mt-3 text-[11px] text-muted">Delegated to {snapshot.activeRun?.provider} · correlation BV-7F2A</p></div></div><div className="rounded-2xl border border-line bg-panel p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Decision stream</h2><span className="text-xs text-muted">Live audit</span></div><div className="space-y-1">{snapshot.activities.map((activity) => <ActivityRow key={activity.id} activity={activity} />)}</div></div></div>
          <div className="space-y-4"><div className="rounded-2xl border border-line bg-panel p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Intelligence matrix</h2><span className="text-xs text-muted">{snapshot.providers.filter((p) => p.status !== 'unavailable').length}/{snapshot.providers.length} ready</span></div><div className="space-y-2">{snapshot.providers.map((provider) => <div key={provider.id} className="flex items-center gap-3 rounded-xl border border-line/70 px-3 py-2.5"><span className={`size-2 rounded-full ${provider.status === 'healthy' ? 'bg-accent' : provider.status === 'ready' ? 'bg-sky-300' : 'bg-muted'}`} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{provider.name}</p><p className="truncate text-[10px] text-muted">{provider.specialty}</p></div><span className="text-[10px] text-muted">{provider.model}</span></div>)}</div></div><div className="rounded-2xl border border-line bg-panel p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">System pulse</h2><span className="text-xs text-accent">3 nominal</span></div><div className="space-y-3">{snapshot.systems.map((system) => <div key={system.label} className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><span className={`size-2 rounded-full ${system.status === 'nominal' ? 'bg-accent' : 'bg-amber-300'}`} /><span className="truncate text-xs">{system.label}</span></div><span className="truncate text-[10px] text-muted">{system.detail}</span></div>)}</div></div></div>
        </div>
        <div className="mt-4 rounded-2xl border border-line bg-panel p-2 shadow-2xl shadow-black/10"><textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); runCommand() } }} placeholder="Command S.A.M. across your BuildVision ecosystem…" aria-label="Command S.A.M." rows={2} className="min-h-14 w-full resize-none bg-transparent px-3 py-2 text-base leading-relaxed outline-none placeholder:text-muted" /><div className="flex items-center justify-between px-2 pb-1"><p className="text-[11px] text-muted">Every command is correlated, delegated, and audited.</p><button onClick={() => runCommand()} disabled={!input.trim() || busy || paused} className="flex size-11 items-center justify-center rounded-xl bg-accent text-background disabled:opacity-40" aria-label="Run command"><ArrowUp size={18} /></button></div></div>
        {messages.length > 0 && <div className="mt-4 space-y-3">{messages.map((message) => <div key={message.id} className="rounded-xl border border-line bg-panel p-4 text-sm leading-relaxed"><span className="mr-2 text-xs font-semibold uppercase tracking-wider text-accent">{message.role === 'user' ? 'Command' : 'S.A.M.'}</span>{message.parts.map((part, i) => part.type === 'text' ? <span key={i} className="whitespace-pre-wrap">{part.text}</span> : null)}</div>)}</div>}{busy && <p className="mt-3 text-xs text-muted">S.A.M. is coordinating intelligence providers…</p>}{error && <p className="mt-3 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-xs text-red-200">Execution stream unavailable. The run was not marked complete.</p>}
      </section>
    </div>
  </main>
}

function SideItem({ icon, label, active = false }: { icon: React.ReactNode; label: string; active?: boolean }) { return <button className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm ${active ? 'bg-panel-strong font-semibold text-foreground' : 'text-muted hover:bg-panel-strong hover:text-foreground'}`}>{icon}{label}</button> }
function SystemRow({ label, status, icon }: { label: string; status: 'nominal' | 'degraded'; icon?: React.ReactNode }) { return <div className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-xs text-muted"><span className="text-muted">{icon ?? <span className={`block size-2 rounded-full ${status === 'nominal' ? 'bg-accent' : 'bg-amber-300'}`} />}</span><span className="flex-1">{label}</span><span className="text-[10px]">{status}</span></div> }
function ActivityRow({ activity }: { activity: SamActivity }) { return <div className="flex gap-3 rounded-xl px-2 py-3 hover:bg-panel-strong"><div className={`mt-1 flex size-7 shrink-0 items-center justify-center rounded-lg ${activity.status === 'blocked' ? 'bg-amber-300/10 text-amber-300' : 'bg-accent-soft text-accent'}`}><Activity size={14} /></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{activity.title}</p><span className="shrink-0 text-[10px] text-muted">{activity.time}</span></div><p className="mt-1 text-xs leading-relaxed text-muted">{activity.detail}</p>{activity.provider && <p className="mt-1 text-[10px] text-accent">via {activity.provider}</p>}</div></div> }
